kafka_version: "3.9.0" 
kafka_user: "kafka"
install_dir: "/opt/kafka"
data_dir: "/var/lib/kafka/data"
log_dir: "/var/log/kafka"
kafka_port: 9092
kafka_internal_port: 9093
cluster_id: "dkedu_kafka_cluster"