---
- name: Configure replication for the replica
  ansible.builtin.lineinfile:
    path: /etc/redis6/redis6.conf
    line: "replicaof {{ redis_primary_host }} {{ redis_port }}"
    state: present

- name: Restart Redis to apply replication changes
  ansible.builtin.service:
    name: redis6
    state: restarted