galaxy_info:
  author: Dmytro Krynytsyn
  description: Ansible role for installing and configuring Elasticsearch
  company: self
  license: MIT
  min_ansible_version: 2.1
  galaxy_tags:
    - elasticsearch
    - search
    - database

dependencies: []