galaxy_info:
  author: Dmytro Krynytsyn
  description: Ansible role for installing and configuring Node Exporter
  company: self
  license: MIT
  min_ansible_version: 2.1
  galaxy_tags:
    - node_exporter
    - monitoring
    - prometheus

dependencies: []