galaxy_info:
  author: Dmytro Krynytsyn
  description: Ansible role for installing common Linux operations tools
  company: self
  license: MIT
  min_ansible_version: 2.1
  galaxy_tags:
    - linux
    - tools
    - operations

dependencies: []